schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"

  types:
    EnvironmentInput:
      type: object
      description: "Input properties for eks environment."
      properties:
        cluster_name:
          type: string
          description: "Cluster Name"
        aws_region:
          type: string
          description: "AWS Region"
          default: "us-east-1"
        vpc_cidr:
          type: string
          description: "VPC CIDR"
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
          default: 10.0.0.0/16
        user:
          type: string
          description: "IAM User for cluster access"
        kubernetes_version:
          type: string
          description: Kubernetes Version
          enum: ["1.20"]
          default: "1.20"
        aws_load_balancer_controller:
          type: boolean
          description: "Enable AWS Load Balancer Controller Add-On"
          default: true
        metrics_server:
          type: boolean
          description: "Enable Metrics Server Add-On"
          default: true
        aws_for_fluentbit:
          type: boolean
          description: "Enable AWS for FluentBit Add-On"
          default: true
        cert_manager:
          type: boolean
          description: "Enable Cert Manager Add-On"
          default: true
        vpa:
          type: boolean
          description: "Enable VPA Add-On"
          default: true
        karpenter:
          type: boolean
          description: "Enable Karpenter Add-On"
          default: true