schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      type: object
      description: "Input properties for eks environment."
      required:
        - cluster_name
        - vpc_cidr
        - user
        - kubernetes_version
      properties:
        cluster_name:
          title: "Cluster name"
          type: string
        vpc_cidr:
          title: "VPC CIDR"
          type: string
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
          default: 10.0.0.0/16
        user:
          title: "User"
          type: string
          description: "IAM User for cluster access"
        kubernetes_version:
          title: "Kubernetes version"
          type: string
          enum: ["1.23"]
          default: "1.23"
        aws_load_balancer_controller:
          title: "Enable AWS Load Balancer Controller Add-On"
          type: boolean
          default: true
        metrics_server:
          title: "Enable Metrics Server Add-On"
          type: boolean
          default: true
        aws_for_fluentbit:
          title: "Enable AWS for FluentBit Add-On"
          type: boolean
          default: true
        cert_manager:
          title: "Enable Cert Manager Add-On"
          type: boolean
          default: true
        vpa:
          title: "Enable VPA Add-On"
          type: boolean
          default: true
        karpenter:
          title: "Enable Karpenter Add-On"
          type: boolean
          default: true
        aws_region:
          title: AWS Region
          type: string
          description: AWS Region where resources will reside
          default: us-east-1
        tf_state_bucket:
          title: Terraform state storage S3 bucket
          type: string
          description: S3 Bucket to store Terraform state
        tf_state_bucket_region:
          title: State bucket AWS Region
          type: string
          description: AWS Region where state bucket resides